<?php

namespace App\Enums;

use App\Models\BioInspector;
use Filament\Support\Contracts\HasLabel;
use Illuminate\Support\HtmlString;
use Illuminate\Support\Str;

/**
 * ISO 3166-1 alpha-2 country codes with German display names.
 *
 * Case names are UpperCamelCase English country names; the backing value is
 * the two-letter code (what is stored); {@see getLabel()} is the German name
 * (what the user searches). Used for the origin country of an organic control
 * body ({@see BioInspector}).
 */
enum Country: string implements HasLabel
{
    case Afghanistan = 'AF';
    case Egypt = 'EG';
    case AlandIslands = 'AX';
    case Albania = 'AL';
    case Algeria = 'DZ';
    case AmericanSamoa = 'AS';
    case Andorra = 'AD';
    case Angola = 'AO';
    case Anguilla = 'AI';
    case Antarctica = 'AQ';
    case AntiguaAndBarbuda = 'AG';
    case EquatorialGuinea = 'GQ';
    case Argentina = 'AR';
    case Armenia = 'AM';
    case Aruba = 'AW';
    case Azerbaijan = 'AZ';
    case Ethiopia = 'ET';
    case Australia = 'AU';
    case Bahamas = 'BS';
    case Bahrain = 'BH';
    case Bangladesh = 'BD';
    case Barbados = 'BB';
    case Belgium = 'BE';
    case Belize = 'BZ';
    case Benin = 'BJ';
    case Bermuda = 'BM';
    case Bhutan = 'BT';
    case Bolivia = 'BO';
    case BonaireSintEustatiusAndSaba = 'BQ';
    case BosniaAndHerzegovina = 'BA';
    case Botswana = 'BW';
    case BouvetIsland = 'BV';
    case Brazil = 'BR';
    case BritishIndianOceanTerritory = 'IO';
    case Brunei = 'BN';
    case Bulgaria = 'BG';
    case BurkinaFaso = 'BF';
    case Burundi = 'BI';
    case CaboVerde = 'CV';
    case Chile = 'CL';
    case China = 'CN';
    case CookIslands = 'CK';
    case CostaRica = 'CR';
    case Curacao = 'CW';
    case Denmark = 'DK';
    case Germany = 'DE';
    case Dominica = 'DM';
    case DominicanRepublic = 'DO';
    case Djibouti = 'DJ';
    case Ecuador = 'EC';
    case ElSalvador = 'SV';
    case IvoryCoast = 'CI';
    case Eritrea = 'ER';
    case Estonia = 'EE';
    case Eswatini = 'SZ';
    case FalklandIslands = 'FK';
    case FaroeIslands = 'FO';
    case Fiji = 'FJ';
    case Finland = 'FI';
    case France = 'FR';
    case FrenchGuiana = 'GF';
    case FrenchPolynesia = 'PF';
    case FrenchSouthernTerritories = 'TF';
    case Gabon = 'GA';
    case Gambia = 'GM';
    case Georgia = 'GE';
    case Ghana = 'GH';
    case Gibraltar = 'GI';
    case Grenada = 'GD';
    case Greece = 'GR';
    case Greenland = 'GL';
    case Guadeloupe = 'GP';
    case Guam = 'GU';
    case Guatemala = 'GT';
    case Guernsey = 'GG';
    case Guinea = 'GN';
    case GuineaBissau = 'GW';
    case Guyana = 'GY';
    case Haiti = 'HT';
    case HeardIslandAndMcDonaldIslands = 'HM';
    case Honduras = 'HN';
    case HongKong = 'HK';
    case India = 'IN';
    case Indonesia = 'ID';
    case Iraq = 'IQ';
    case Iran = 'IR';
    case Ireland = 'IE';
    case Iceland = 'IS';
    case Israel = 'IL';
    case Italy = 'IT';
    case Jamaica = 'JM';
    case Japan = 'JP';
    case Yemen = 'YE';
    case Jersey = 'JE';
    case Jordan = 'JO';
    case CaymanIslands = 'KY';
    case Cambodia = 'KH';
    case Cameroon = 'CM';
    case Canada = 'CA';
    case Kazakhstan = 'KZ';
    case Qatar = 'QA';
    case Kenya = 'KE';
    case Kyrgyzstan = 'KG';
    case Kiribati = 'KI';
    case CocosIslands = 'CC';
    case Colombia = 'CO';
    case Comoros = 'KM';
    case DemocraticRepublicOfTheCongo = 'CD';
    case RepublicOfTheCongo = 'CG';
    case Croatia = 'HR';
    case Cuba = 'CU';
    case Kuwait = 'KW';
    case Laos = 'LA';
    case Lesotho = 'LS';
    case Latvia = 'LV';
    case Lebanon = 'LB';
    case Liberia = 'LR';
    case Libya = 'LY';
    case Liechtenstein = 'LI';
    case Lithuania = 'LT';
    case Luxembourg = 'LU';
    case Macau = 'MO';
    case Madagascar = 'MG';
    case Malawi = 'MW';
    case Malaysia = 'MY';
    case Maldives = 'MV';
    case Mali = 'ML';
    case Malta = 'MT';
    case Morocco = 'MA';
    case MarshallIslands = 'MH';
    case Martinique = 'MQ';
    case Mauritania = 'MR';
    case Mauritius = 'MU';
    case Mayotte = 'YT';
    case Mexico = 'MX';
    case Micronesia = 'FM';
    case Moldova = 'MD';
    case Monaco = 'MC';
    case Mongolia = 'MN';
    case Montenegro = 'ME';
    case Montserrat = 'MS';
    case Mozambique = 'MZ';
    case Myanmar = 'MM';
    case Namibia = 'NA';
    case Nauru = 'NR';
    case Nepal = 'NP';
    case NewCaledonia = 'NC';
    case NewZealand = 'NZ';
    case Nicaragua = 'NI';
    case Netherlands = 'NL';
    case Niger = 'NE';
    case Nigeria = 'NG';
    case Niue = 'NU';
    case NorthKorea = 'KP';
    case NorthMacedonia = 'MK';
    case NorthernMarianaIslands = 'MP';
    case NorfolkIsland = 'NF';
    case Norway = 'NO';
    case Oman = 'OM';
    case Austria = 'AT';
    case Pakistan = 'PK';
    case Palestine = 'PS';
    case Palau = 'PW';
    case Panama = 'PA';
    case PapuaNewGuinea = 'PG';
    case Paraguay = 'PY';
    case Peru = 'PE';
    case Philippines = 'PH';
    case PitcairnIslands = 'PN';
    case Poland = 'PL';
    case Portugal = 'PT';
    case PuertoRico = 'PR';
    case Reunion = 'RE';
    case Rwanda = 'RW';
    case Romania = 'RO';
    case Russia = 'RU';
    case SolomonIslands = 'SB';
    case Zambia = 'ZM';
    case Samoa = 'WS';
    case SanMarino = 'SM';
    case SaoTomeAndPrincipe = 'ST';
    case SaudiArabia = 'SA';
    case Sweden = 'SE';
    case Switzerland = 'CH';
    case Senegal = 'SN';
    case Serbia = 'RS';
    case Seychelles = 'SC';
    case SierraLeone = 'SL';
    case Zimbabwe = 'ZW';
    case Singapore = 'SG';
    case SintMaarten = 'SX';
    case Slovakia = 'SK';
    case Slovenia = 'SI';
    case Somalia = 'SO';
    case Spain = 'ES';
    case SriLanka = 'LK';
    case SaintBarthelemy = 'BL';
    case SaintHelena = 'SH';
    case SaintKittsAndNevis = 'KN';
    case SaintLucia = 'LC';
    case SaintMartin = 'MF';
    case SaintPierreAndMiquelon = 'PM';
    case SaintVincentAndTheGrenadines = 'VC';
    case SouthAfrica = 'ZA';
    case Sudan = 'SD';
    case SouthGeorgiaAndTheSouthSandwichIslands = 'GS';
    case SouthKorea = 'KR';
    case SouthSudan = 'SS';
    case Suriname = 'SR';
    case SvalbardAndJanMayen = 'SJ';
    case Syria = 'SY';
    case Tajikistan = 'TJ';
    case Taiwan = 'TW';
    case Tanzania = 'TZ';
    case Thailand = 'TH';
    case TimorLeste = 'TL';
    case Togo = 'TG';
    case Tokelau = 'TK';
    case Tonga = 'TO';
    case TrinidadAndTobago = 'TT';
    case Chad = 'TD';
    case Czechia = 'CZ';
    case Tunisia = 'TN';
    case Turkey = 'TR';
    case Turkmenistan = 'TM';
    case TurksAndCaicosIslands = 'TC';
    case Tuvalu = 'TV';
    case Uganda = 'UG';
    case Ukraine = 'UA';
    case Hungary = 'HU';
    case UnitedStatesMinorOutlyingIslands = 'UM';
    case Uruguay = 'UY';
    case Uzbekistan = 'UZ';
    case Vanuatu = 'VU';
    case VaticanCity = 'VA';
    case Venezuela = 'VE';
    case UnitedArabEmirates = 'AE';
    case UnitedStates = 'US';
    case UnitedKingdom = 'GB';
    case Vietnam = 'VN';
    case WallisAndFutuna = 'WF';
    case ChristmasIsland = 'CX';
    case Belarus = 'BY';
    case WesternSahara = 'EH';
    case CentralAfricanRepublic = 'CF';
    case Cyprus = 'CY';
    case BritishVirginIslands = 'VG';
    case UnitedStatesVirginIslands = 'VI';

    public function getLabel(): string
    {
        return match ($this) {
            self::Afghanistan => 'Afghanistan',
            self::Egypt => 'Ägypten',
            self::AlandIslands => 'Ålandinseln',
            self::Albania => 'Albanien',
            self::Algeria => 'Algerien',
            self::AmericanSamoa => 'Amerikanisch-Samoa',
            self::Andorra => 'Andorra',
            self::Angola => 'Angola',
            self::Anguilla => 'Anguilla',
            self::Antarctica => 'Antarktis',
            self::AntiguaAndBarbuda => 'Antigua und Barbuda',
            self::EquatorialGuinea => 'Äquatorialguinea',
            self::Argentina => 'Argentinien',
            self::Armenia => 'Armenien',
            self::Aruba => 'Aruba',
            self::Azerbaijan => 'Aserbaidschan',
            self::Ethiopia => 'Äthiopien',
            self::Australia => 'Australien',
            self::Bahamas => 'Bahamas',
            self::Bahrain => 'Bahrain',
            self::Bangladesh => 'Bangladesch',
            self::Barbados => 'Barbados',
            self::Belgium => 'Belgien',
            self::Belize => 'Belize',
            self::Benin => 'Benin',
            self::Bermuda => 'Bermuda',
            self::Bhutan => 'Bhutan',
            self::Bolivia => 'Bolivien',
            self::BonaireSintEustatiusAndSaba => 'Bonaire, Sint Eustatius und Saba',
            self::BosniaAndHerzegovina => 'Bosnien und Herzegowina',
            self::Botswana => 'Botswana',
            self::BouvetIsland => 'Bouvetinsel',
            self::Brazil => 'Brasilien',
            self::BritishIndianOceanTerritory => 'Britisches Territorium im Indischen Ozean',
            self::Brunei => 'Brunei Darussalam',
            self::Bulgaria => 'Bulgarien',
            self::BurkinaFaso => 'Burkina Faso',
            self::Burundi => 'Burundi',
            self::CaboVerde => 'Cabo Verde',
            self::Chile => 'Chile',
            self::China => 'China',
            self::CookIslands => 'Cookinseln',
            self::CostaRica => 'Costa Rica',
            self::Curacao => 'Curaçao',
            self::Denmark => 'Dänemark',
            self::Germany => 'Deutschland',
            self::Dominica => 'Dominica',
            self::DominicanRepublic => 'Dominikanische Republik',
            self::Djibouti => 'Dschibuti',
            self::Ecuador => 'Ecuador',
            self::ElSalvador => 'El Salvador',
            self::IvoryCoast => 'Elfenbeinküste',
            self::Eritrea => 'Eritrea',
            self::Estonia => 'Estland',
            self::Eswatini => 'Eswatini',
            self::FalklandIslands => 'Falklandinseln',
            self::FaroeIslands => 'Färöer',
            self::Fiji => 'Fidschi',
            self::Finland => 'Finnland',
            self::France => 'Frankreich',
            self::FrenchGuiana => 'Französisch-Guayana',
            self::FrenchPolynesia => 'Französisch-Polynesien',
            self::FrenchSouthernTerritories => 'Französische Süd- und Antarktisgebiete',
            self::Gabon => 'Gabun',
            self::Gambia => 'Gambia',
            self::Georgia => 'Georgien',
            self::Ghana => 'Ghana',
            self::Gibraltar => 'Gibraltar',
            self::Grenada => 'Grenada',
            self::Greece => 'Griechenland',
            self::Greenland => 'Grönland',
            self::Guadeloupe => 'Guadeloupe',
            self::Guam => 'Guam',
            self::Guatemala => 'Guatemala',
            self::Guernsey => 'Guernsey',
            self::Guinea => 'Guinea',
            self::GuineaBissau => 'Guinea-Bissau',
            self::Guyana => 'Guyana',
            self::Haiti => 'Haiti',
            self::HeardIslandAndMcDonaldIslands => 'Heard und McDonaldinseln',
            self::Honduras => 'Honduras',
            self::HongKong => 'Hongkong',
            self::India => 'Indien',
            self::Indonesia => 'Indonesien',
            self::Iraq => 'Irak',
            self::Iran => 'Iran',
            self::Ireland => 'Irland',
            self::Iceland => 'Island',
            self::Israel => 'Israel',
            self::Italy => 'Italien',
            self::Jamaica => 'Jamaika',
            self::Japan => 'Japan',
            self::Yemen => 'Jemen',
            self::Jersey => 'Jersey',
            self::Jordan => 'Jordanien',
            self::CaymanIslands => 'Kaimaninseln',
            self::Cambodia => 'Kambodscha',
            self::Cameroon => 'Kamerun',
            self::Canada => 'Kanada',
            self::Kazakhstan => 'Kasachstan',
            self::Qatar => 'Katar',
            self::Kenya => 'Kenia',
            self::Kyrgyzstan => 'Kirgisistan',
            self::Kiribati => 'Kiribati',
            self::CocosIslands => 'Kokosinseln',
            self::Colombia => 'Kolumbien',
            self::Comoros => 'Komoren',
            self::DemocraticRepublicOfTheCongo => 'Kongo (Demokratische Republik)',
            self::RepublicOfTheCongo => 'Kongo (Republik)',
            self::Croatia => 'Kroatien',
            self::Cuba => 'Kuba',
            self::Kuwait => 'Kuwait',
            self::Laos => 'Laos',
            self::Lesotho => 'Lesotho',
            self::Latvia => 'Lettland',
            self::Lebanon => 'Libanon',
            self::Liberia => 'Liberia',
            self::Libya => 'Libyen',
            self::Liechtenstein => 'Liechtenstein',
            self::Lithuania => 'Litauen',
            self::Luxembourg => 'Luxemburg',
            self::Macau => 'Macau',
            self::Madagascar => 'Madagaskar',
            self::Malawi => 'Malawi',
            self::Malaysia => 'Malaysia',
            self::Maldives => 'Malediven',
            self::Mali => 'Mali',
            self::Malta => 'Malta',
            self::Morocco => 'Marokko',
            self::MarshallIslands => 'Marshallinseln',
            self::Martinique => 'Martinique',
            self::Mauritania => 'Mauretanien',
            self::Mauritius => 'Mauritius',
            self::Mayotte => 'Mayotte',
            self::Mexico => 'Mexiko',
            self::Micronesia => 'Mikronesien',
            self::Moldova => 'Moldau',
            self::Monaco => 'Monaco',
            self::Mongolia => 'Mongolei',
            self::Montenegro => 'Montenegro',
            self::Montserrat => 'Montserrat',
            self::Mozambique => 'Mosambik',
            self::Myanmar => 'Myanmar',
            self::Namibia => 'Namibia',
            self::Nauru => 'Nauru',
            self::Nepal => 'Nepal',
            self::NewCaledonia => 'Neukaledonien',
            self::NewZealand => 'Neuseeland',
            self::Nicaragua => 'Nicaragua',
            self::Netherlands => 'Niederlande',
            self::Niger => 'Niger',
            self::Nigeria => 'Nigeria',
            self::Niue => 'Niue',
            self::NorthKorea => 'Nordkorea',
            self::NorthMacedonia => 'Nordmazedonien',
            self::NorthernMarianaIslands => 'Nördliche Marianen',
            self::NorfolkIsland => 'Norfolkinsel',
            self::Norway => 'Norwegen',
            self::Oman => 'Oman',
            self::Austria => 'Österreich',
            self::Pakistan => 'Pakistan',
            self::Palestine => 'Palästina',
            self::Palau => 'Palau',
            self::Panama => 'Panama',
            self::PapuaNewGuinea => 'Papua-Neuguinea',
            self::Paraguay => 'Paraguay',
            self::Peru => 'Peru',
            self::Philippines => 'Philippinen',
            self::PitcairnIslands => 'Pitcairninseln',
            self::Poland => 'Polen',
            self::Portugal => 'Portugal',
            self::PuertoRico => 'Puerto Rico',
            self::Reunion => 'Réunion',
            self::Rwanda => 'Ruanda',
            self::Romania => 'Rumänien',
            self::Russia => 'Russland',
            self::SolomonIslands => 'Salomonen',
            self::Zambia => 'Sambia',
            self::Samoa => 'Samoa',
            self::SanMarino => 'San Marino',
            self::SaoTomeAndPrincipe => 'São Tomé und Príncipe',
            self::SaudiArabia => 'Saudi-Arabien',
            self::Sweden => 'Schweden',
            self::Switzerland => 'Schweiz',
            self::Senegal => 'Senegal',
            self::Serbia => 'Serbien',
            self::Seychelles => 'Seychellen',
            self::SierraLeone => 'Sierra Leone',
            self::Zimbabwe => 'Simbabwe',
            self::Singapore => 'Singapur',
            self::SintMaarten => 'Sint Maarten',
            self::Slovakia => 'Slowakei',
            self::Slovenia => 'Slowenien',
            self::Somalia => 'Somalia',
            self::Spain => 'Spanien',
            self::SriLanka => 'Sri Lanka',
            self::SaintBarthelemy => 'Saint-Barthélemy',
            self::SaintHelena => 'St. Helena',
            self::SaintKittsAndNevis => 'St. Kitts und Nevis',
            self::SaintLucia => 'St. Lucia',
            self::SaintMartin => 'Saint-Martin',
            self::SaintPierreAndMiquelon => 'Saint-Pierre und Miquelon',
            self::SaintVincentAndTheGrenadines => 'St. Vincent und die Grenadinen',
            self::SouthAfrica => 'Südafrika',
            self::Sudan => 'Sudan',
            self::SouthGeorgiaAndTheSouthSandwichIslands => 'Südgeorgien und die Südlichen Sandwichinseln',
            self::SouthKorea => 'Südkorea',
            self::SouthSudan => 'Südsudan',
            self::Suriname => 'Suriname',
            self::SvalbardAndJanMayen => 'Svalbard und Jan Mayen',
            self::Syria => 'Syrien',
            self::Tajikistan => 'Tadschikistan',
            self::Taiwan => 'Taiwan',
            self::Tanzania => 'Tansania',
            self::Thailand => 'Thailand',
            self::TimorLeste => 'Timor-Leste',
            self::Togo => 'Togo',
            self::Tokelau => 'Tokelau',
            self::Tonga => 'Tonga',
            self::TrinidadAndTobago => 'Trinidad und Tobago',
            self::Chad => 'Tschad',
            self::Czechia => 'Tschechien',
            self::Tunisia => 'Tunesien',
            self::Turkey => 'Türkei',
            self::Turkmenistan => 'Turkmenistan',
            self::TurksAndCaicosIslands => 'Turks- und Caicosinseln',
            self::Tuvalu => 'Tuvalu',
            self::Uganda => 'Uganda',
            self::Ukraine => 'Ukraine',
            self::Hungary => 'Ungarn',
            self::UnitedStatesMinorOutlyingIslands => 'United States Minor Outlying Islands',
            self::Uruguay => 'Uruguay',
            self::Uzbekistan => 'Usbekistan',
            self::Vanuatu => 'Vanuatu',
            self::VaticanCity => 'Vatikanstadt',
            self::Venezuela => 'Venezuela',
            self::UnitedArabEmirates => 'Vereinigte Arabische Emirate',
            self::UnitedStates => 'Vereinigte Staaten',
            self::UnitedKingdom => 'Vereinigtes Königreich',
            self::Vietnam => 'Vietnam',
            self::WallisAndFutuna => 'Wallis und Futuna',
            self::ChristmasIsland => 'Weihnachtsinsel',
            self::Belarus => 'Weißrussland',
            self::WesternSahara => 'Westsahara',
            self::CentralAfricanRepublic => 'Zentralafrikanische Republik',
            self::Cyprus => 'Zypern',
            self::BritishVirginIslands => 'Britische Jungferninseln',
            self::UnitedStatesVirginIslands => 'Amerikanische Jungferninseln',
        };
    }

    /**
     * Blade-icon name of this country's flag (outhebox/blade-flags), e.g.
     * "flag-country-de".
     */
    public function flagIcon(): string
    {
        return 'flag-country-'.Str::lower($this->value);
    }

    /**
     * German country name preceded by its inline flag, as HTML. Used for
     * Filament option labels and table columns (both need allowHtml/html).
     */
    public function flaggedLabel(): HtmlString
    {
        $flag = svg($this->flagIcon(), attributes: [
            'width' => 20,
            'height' => 15,
            'style' => 'display:inline-block;border-radius:2px;vertical-align:middle;',
        ])->toHtml();

        return new HtmlString(
            '<span style="display:inline-flex;align-items:center;gap:0.5rem;">'
            .$flag
            .'<span>'.e($this->getLabel()).'</span></span>'
        );
    }
}
